CREATE TABLE account (
    id            TEXT PRIMARY KEY,
    created_at    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_suspicious BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE invoice (
    id         TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES account (id),
    amount     DOUBLE PRECISION NOT NULL,
    status     VARCHAR(20) NOT NULL CHECK (status IN ('APPROVED', 'REJECTED')),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fraud_history (
    id          TEXT PRIMARY KEY,
    invoice_id  TEXT NOT NULL UNIQUE REFERENCES invoice (id),
    reason      VARCHAR(30) NOT NULL CHECK (reason IN ('SUSPICIOUS_ACCOUNT', 'UNUSUAL_PATTERN', 'FREQUENT_HIGH_VALUE')),
    description TEXT,
    created_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
